<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE4tuuyy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE4tuuyy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE4tuuyy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerE4tuuyy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerE4tuuyy\appProdProjectContainer([
    'container.build_hash' => 'E4tuuyy',
    'container.build_id' => '97134b36',
    'container.build_time' => 1574174111,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE4tuuyy');
