<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGasfjv0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGasfjv0/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGasfjv0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGasfjv0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGasfjv0\appProdProjectContainer([
    'container.build_hash' => 'Gasfjv0',
    'container.build_id' => 'cd8b2a6b',
    'container.build_time' => 1571738869,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGasfjv0');
